name: deploy

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .

    - name: Build demo application
      run: MJSWAN_BASE_PATH="/mjswan/" MJSWAN_NO_LAUNCH=1 python examples/demo/full.py

    - name: Deploy to gh-pages branch
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./examples/demo/dist
